routes/web.php
<?php

Auth::routes();

Route::group(['middleware' => 'auth'], function (){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('faqs', 'FaqsController');
    Route::post('/faqs/publish', 'FaqsController@publish')->name('faqs.publish');
    Route::get('/faqs/index/{link}', 'FaqsController@link')->name('faqs.index.link');
    Route::resource('themes', 'ThemesController');
    Route::resource('users', 'UsersController');
});

Route::resource('guests', 'GuestsController');
Route::get('/', 'PagesController@index')->name('pages.index');

app/Theme.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Theme extends Model
{
    protected $fillable = [
        'title',
    ];

    public function faqs()
    {
        return $this->hasMany('App\faq');
    }
}

app/Http/Controllers/ThemesController.php
<?php

namespace App\Http\Controllers;

use App\Faq;
use App\Theme;
use Illuminate\Http\Request;

class ThemesController extends Controller
{
    public function index()
    {
        $themes = Theme::paginate(10);
        return view('admin.themes.index', compact('themes'));
    }

    public function create()
    {
        return view('admin.themes.form');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
        ]);
        Theme::create($request->all());
        return redirect()->route('themes.index');
    }

    public function edit(Theme $theme)
    {
        $entity = $theme;
        return view('admin.themes.form', compact('entity'));
    }

    public function update(Request $request, Theme $theme)
    {
        $this->validate($request, [
            'title' => 'required',
        ]);
        $theme->update($request->all());

        return redirect()->route('themes.index');
    }


    public function destroy(Theme $theme)
    {
        $theme->delete();
        return redirect()->route('themes.index');
    }

}

resources/views/admin/themes/form.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<div class="panel panel-default">
					@if(empty($entity))
						<div class="panel-heading">Create new theme</div>
					@else
						<div class="panel-heading">Edit theme</div>
					@endif
					<div class="panel-body">
						<form action="@if(empty($entity)){{ route('themes.store') }}@else{{ route('themes.update', $entity->id) }}@endif" method="POST">
							{{ csrf_field() }}
							@isset($entity)
								 {{ method_field('PUT') }}
							@endisset
							<div class="row">
								@include('admin.fields.textTheme', ['field' => 'title', 'name' => 'Title'])
							</div>
							<input type="submit" value="save">
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/admin/themes/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <h2 class="panel-heading">Main menu</h2>
                    <div class="text-center">
                        <div class="col-md-6 " style="margin-bottom: 10px"><a type="button" class="btn btn-success"
                                                                              href="{{ route('faqs.create') }}">Creat
                                new question</a></div>
                        <div class="col-md-6" style="margin-bottom: 10px"><a type="button" class="btn btn-success"
                                                                             href="{{ route('themes.create') }}">Creat
                                new themes</a></div>
                    </div>
                    <div class="panel-body">
                        @if($themes->count() > 0)
                            <table class="table">
                                <tr>
                                    <th>ID</th>
                                    <th>Theme</th>
                                    <th>Count</th>
                                    <th>Publish</th>
                                    <th>No answer</th>
                                    <th>Actions</th>
                                </tr>
                                @foreach($themes as $theme)
                                    <tr>
                                        <td>{{ $theme->id }}</td>
                                        <td>
                                            <a type="button" class="btn btn-primary"
                                               href="{{ route('faqs.index.link', $theme->id) }}">{{ $theme->title }}</a>
                                        </td>
                                        <td>{{ $theme->faqs->count() }}</td>
                                        <td>{{ $theme->faqs->where('publish', '2')->count() }}</td>
                                        <td>{{ $theme->faqs->where('status', '0')->count() }}</td>
                                        <td>
                                            <form action="{{ route('themes.destroy', $theme->id) }}" method="POST">
                                                <a type="button" class="btn btn-default"
                                                   href="{{ route('themes.edit', $theme->id) }}">edit</a>
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                                <button type="submit" class="btn btn-danger">delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </table>
                            <div class="text-center">
                                <a type="button" class="btn btn-primary"
                                   href="{{ route('faqs.index.link', 'noanswer') }}">All question without answer</a>
                            </div>
                            <div class="text-center">{{$themes->render()}}</div>
                        @else
                            No themes
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection