routes/web.php
<?php

Auth::routes();

Route::group(['middleware' => 'auth'], function (){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('faqs', 'FaqsController');
    Route::post('/faqs/publish', 'FaqsController@publish')->name('faqs.publish');
    Route::get('/faqs/index/{link}', 'FaqsController@link')->name('faqs.index.link');
    Route::resource('themes', 'ThemesController');
    Route::resource('users', 'UsersController');
});

Route::resource('guests', 'GuestsController');
Route::get('/', 'PagesController@index')->name('pages.index');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;


    protected $fillable = [
        'name', 'email', 'password',
    ];


    protected $hidden = [
        'password', 'remember_token',
    ];

    public function faqs()
    {
        return $this->hasOne('App\faq');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{

    public function index()
    {
        return view('admin.users.index', [
            'users' => User::paginate(10)
        ]);
    }

    function create()
    {
        return view('admin.users.form');
    }

    public function store(Request $request)
    {
        $validator = $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
        ]);

        User::create([
            'name' => $request['name'],
            'email' => $request['email'],
            'password' => bcrypt($request['password'])
        ]);
        return redirect()->route('users.index');
    }

    public function edit(User $user)
    {
        $entity = $user;
        return view('admin.users.form', compact('user', 'entity'));
    }

    public function update(Request $request, User $user)
    {
        $validator = $request->validate([
            'name' => 'required|string|max:255',
            'email' => [
                'required',
                'string',
                'email',
                'max:255',
                \Illuminate\Validation\Rule::unique('users')->ignore($user->id),
            ],
            'password' => 'nullable|string|min:6|confirmed',
        ]);

        $user->name = $request['name'];
        $user->email = $request['email'];
        $request['password'] == null ?: $user->password = bcrypt($request['password']);
        $user->save();
        return redirect()->route('users.index');
    }

    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route('users.index');
    }
}

resources/views/admin/users/form.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<div class="panel panel-default">
					@if(empty($entity))
						<div class="panel-heading">Create new user</div>
					@else
						<div class="panel-heading">Edit user</div>
					@endif

					@if($errors->any())
						<div class="alert alert-danger">
							<ul>
								@foreach($errors->all() as $error)
									<li>{{ $error }}</li>
								@endforeach
							</ul>
						</div>
					@endif
					<div class="panel-body">
						<form action="@if(empty($entity)){{ route('users.store') }}@else{{ route('users.update', $entity->id) }}@endif" method="POST">
							{{ csrf_field() }}
							@isset($entity)
								 {{ method_field('PUT') }}
							@endisset
							<div class="row">
								{{ csrf_field() }}
								@include('admin.fields.anything', ['type' => 'text', 'field' => 'name', 'name' => 'Name'])
								@include('admin.fields.anything', ['type' => 'email', 'field' => 'email', 'name' => 'E-Mail'])
								@include('admin.fields.password', ['type' => 'password', 'field' => 'password', 'name' => 'Password'])
								@include('admin.fields.password', ['type' => 'password', 'field' => 'password_confirmation', 'name' => 'Confirm Password'])
							</div>
							<input type="submit" value="Register">
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<div class="panel panel-default">
					<h2 class="panel-heading">Administrators</h2>
					<div class="text-center">
						<div class="col-md-6 " style="margin-bottom: 10px"><a type="button" class="btn btn-success" href="{{ route('users.create') }}">Create new administrator</a></div>
					</div>
					<div class="panel-body">
						@if($users->count() > 0)
							<table class="table">
								<tr>
									<th>ID</th>
									<th>Name</th>
									<th>Mail</th>
									<th>Actions</th>
								</tr>
								@foreach($users as $user)
									<tr>
										<td>{{ $user->id }}</td>
										<td>{{ $user->name }}</td>
										<td>{{ $user->email }}</td>
										<td>
											<form action="{{ route('users.destroy', $user->id) }}" method="POST">
												<a type="button" class="btn btn-default" href="{{ route('users.edit', $user->id) }}">edit</a>
												{{ method_field('DELETE') }}
												{{ csrf_field() }}
												<button type="submit" class="btn btn-danger">delete</button>
											</form>
										</td>
									</tr>
								@endforeach
							</table>
							<div class="text-center">
								<a type="button" class="btn btn-primary" href="{{ route('themes.index') }}">Main menu</a>
							</div>
							<div class="text-center">{{$users->render()}}</div>
						@else
							No users
						@endif
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection