routes/web.php
<?php

Auth::routes();

Route::group(['middleware' => 'auth'], function (){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('faqs', 'FaqsController');
    Route::post('/faqs/publish', 'FaqsController@publish')->name('faqs.publish');
    Route::get('/faqs/index/{link}', 'FaqsController@link')->name('faqs.index.link');
    Route::resource('themes', 'ThemesController');
    Route::resource('users', 'UsersController');
});

Route::resource('guests', 'GuestsController');
Route::get('/', 'PagesController@index')->name('pages.index');

app/Faq.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Faq extends Model
{

    protected $fillable = [
        'status',
        'publish',
        'question',
        'answer',
        'user_id',
        'theme_id'
    ];

    public function scopeNoanswer($query)
    {
        return $query->where('status', '0');
    }

    public function scopeLink($query, $link)
    {
        return $query->where('theme_id', $link);
    }

    public function theme()
    {
        return $this->belongsTo('App\Theme');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/FaqsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use App\Faq;
use App\Theme;
use App\User;
use Illuminate\Http\Request;

class FaqsController extends Controller
{
    public function index()
    {
        $faqs = Faq::paginate(10);
        return view('admin.faqs.index', compact('faqs'));
    }

    public function create()
    {
        $themes = Theme::all();
        return view('admin.faqs.form', compact('themes'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'theme_id' => 'required|integer',
        ]);
        $data = $request->all();
        $data['status'] = ($request->has('answer') && $data['answer'] !== null) ? 1 : 0;
        $data['user_id'] = Auth::user()->id;
        Faq::create($data);
        return redirect()->route('themes.index');
    }

    public function edit(faq $faq)
    {
        $entity = $faq;
        $themes = Theme::all();
        return view('admin.faqs.form', compact('themes', 'entity'));
    }

    public function update(Request $request, Faq $faq)
    {
        $this->validate($request, [
            'name' => 'required',
            'question' => 'required',
            'theme_id' => 'required|integer'
        ]);
        $data = $request->all();
        $data['status'] = ($request->has('answer') && $data['answer'] !== null) ? 1 : 0;
        User::find($faq->user_id)->update(['name' => $request->name]);
        $faq->update($data);
        return redirect()->route('themes.index');
    }


    public function destroy(Faq $faq)
    {
        $faq->delete();
        return redirect()->back();
    }

    public function publish(Request $request)
    {
        Faq::find($request->id)->update(['publish' => $request->publish]);
        return redirect()->back();
    }

    public function link($link)
    {

        if ($link == 'noanswer') {
            $link = 'noanswer';
            $faqs = Faq::noanswer()->paginate(10);
        }elseif($link == 'login'){
            return redirect()->route('themes.index');
        }else{
            $faqs = Faq::link($link)->paginate(10);
            $link = Theme::find($link)->value('title');
        }

        return view('admin.faqs.index', compact('faqs', 'link'));
    }

}

resources/views/admin/faqs/form.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<div class="panel panel-default">
					@if(empty($entity))
						<div class="panel-heading">Create new faq</div>
					@else
						<div class="panel-heading">Edit faq</div>
					@endif
					<div class="panel-body">
						<form action="@if(empty($entity)){{ route('faqs.store') }}@else{{ route('faqs.update', $entity->id) }}@endif" method="POST">
							{{ csrf_field() }}
							@isset($entity)
								{{ method_field('PUT') }}
							@endisset
							<div class="row">
                                @if(!empty($entity))
                                	@include('admin.fields.text', ['field' => 'name', 'name' => 'author', 'entity' => $entity->user->name])
                                @endif
                                @include('admin.fields.textarea', ['field' => 'question', 'name' => 'Question', 'rows' => 2])
                                @include('admin.fields.textarea', ['field' => 'answer', 'name' => 'Answer', 'rows' => 5])
                                @include('admin.fields.select', ['field' => 'theme_id', 'name' => 'Theme', 'options' => $themes])
							</div>
							<p class="text-center"><input type="checkbox" name="publish" value="2">Click if your want to publish?</p>
							<input type="submit" class="btn btn-info" value="save">
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/admin/faqs/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<h2 class="panel-heading">FAQ\{{isset($link) ? $link : '' }}</h2>
					<div class="panel-body">
						@if($faqs->count() > 0)
							<table class="table text-center">
								<tr>
									<th>Date create</th>
									<th class="text-center">Question</th>
									<th class="text-center">Status</th>
									<th class="text-center">Author</th>
									<th class="text-center">Condition</th>
									<th class="text-center">Actions</th>
								</tr>
								@foreach($faqs as $faq)

									<tr>
										<td>{{ $faq->created_at }}</td>
										<td class="text-left">{{(mb_strlen($faq->question) > 40) ? mb_substr($faq->question, 0, 40) . "..." : mb_substr($faq->question, 0, 40)}}</td>
										@if($faq->status == 0)
											<td>no answer</td>
										@else
											<td>answer</td>
										@endif

										<td>{{$faq->user->name}}</td>
										<td>
											<form action="{{ route('faqs.publish') }}" method="POST">
												{{ csrf_field() }}
												<input type="hidden" name="id" value="{{$faq->id}}">
												<input type="hidden" name="publish" value="{{$faq->publish}}">
													<button type="submit" name='publish' value="0" class="btn {{($faq->publish == '0') ? "btn-info" : "btn-default"}}">hidden</button>
													<button type="submit" name='publish' value="1" class="btn {{($faq->publish == '1') ? "btn-warning" : "btn-default"}}">expect an answer</button>
													<button type="submit" name='publish' value="2" class="btn {{($faq->publish == '2') ? "btn-success" : "btn-default"}}">publish</button>
											</form>
										</td>
										<td>
											<form action="{{ route('faqs.destroy', $faq->id) }}" method="POST">
												<a type="button" class="btn btn-warning" href="{{ route('faqs.edit', $faq->id) }}">edit</a>
												<input type="hidden" name="link" value="{{$link}}">
												{{ method_field('DELETE') }}
												{{ csrf_field() }}
												<button type="submit" class="btn btn-danger">delete</button>
											</form>
										</td>
									</tr>
								@endforeach
							</table>
							<div class="text-center">
								<a type="button" class="btn btn-primary" href="{{ route('themes.index') }}">Main menu</a>
							</div>
							<div class="text-center">{{$faqs->render()}}</div>
						@else
							No faqs
						@endif
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection